import { StyleSheet } from 'react-native';
import { COLORS, RADII, SHADOWS, FONTS } from '../../../constants/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.darker,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 24,
        paddingVertical: 40,
    },
    contentContainer: {
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
    },
    headerSection: {
        alignItems: 'center',
        marginBottom: 48,
    },
    logo: {
        width: 80,
        height: 80,
        marginBottom: 24,
        borderRadius: RADII.circle,
        backgroundColor: COLORS.glass,
        resizeMode: 'contain',
        ...SHADOWS.softPrimary,
    },
    welcomeText: {
        color: COLORS.light,
        fontSize: 32,
        fontWeight: '700',
        fontFamily: FONTS.heading,
        marginBottom: 8,
        textAlign: 'center',
    },
    subtitle: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.body,
        textAlign: 'center',
        opacity: 0.8,
    },
    formSection: {
        width: '100%',
        marginBottom: 32,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        height: 56,
        backgroundColor: COLORS.glass,
        borderRadius: RADII.rounded,
        marginBottom: 16,
        paddingHorizontal: 20,
        borderWidth: 1,
        borderColor: 'rgba(197, 198, 199, 0.1)',
        ...SHADOWS.card,
    },
    inputFocused: {
        borderColor: COLORS.primary,
        borderWidth: 2,
        ...SHADOWS.softPrimary,
    },
    input: {
        flex: 1,
        color: COLORS.light,
        fontSize: 16,
        fontFamily: FONTS.body,
        paddingVertical: 0,
    },
    eyeIcon: {
        padding: 8,
        borderRadius: RADII.rounded,
    },
    forgotPassword: {
        alignSelf: 'flex-end',
        marginTop: 8,
        marginBottom: 24,
    },
    forgotPasswordText: {
        color: COLORS.accent,
        fontSize: 14,
        fontFamily: FONTS.body,
        fontWeight: '500',
    },
    loginButton: {
        backgroundColor: COLORS.primary,
        width: '100%',
        height: 56,
        borderRadius: RADII.rounded,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 32,
        ...SHADOWS.btnPrimary,
    },
    loginButtonPressed: {
        ...SHADOWS.btnPrimaryHover,
        transform: [{ scale: 0.98 }],
    },
    loginButtonText: {
        color: COLORS.light,
        fontSize: 18,
        fontWeight: '600',
        fontFamily: FONTS.body,
    },
    dividerSection: {
        width: '100%',
        marginBottom: 32,
    },
    orContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
    },
    line: {
        flex: 1,
        height: 1,
        backgroundColor: 'rgba(197, 198, 199, 0.2)',
    },
    orText: {
        color: COLORS.text,
        marginHorizontal: 16,
        fontSize: 14,
        fontFamily: FONTS.body,
        opacity: 0.7,
    },
    socialSection: {
        width: '100%',
        marginBottom: 40,
    },
    socialButtonsContainer: {
        width: '100%',
        alignItems: 'center',
    },
    googleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
        height: 56,
        backgroundColor: COLORS.light,
        borderRadius: RADII.rounded,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.1)',
        ...SHADOWS.card,
    },
    googleButtonPressed: {
        backgroundColor: '#f8f9fa',
        ...SHADOWS.btnSecondaryHover,
        transform: [{ scale: 0.98 }],
    },
    googleButtonDisabled: {
        backgroundColor: 'rgba(248, 249, 250, 0.5)',
        opacity: 0.6,
    },
    googleIcon: {
        marginRight: 12,
    },
    googleLogoImage: {
        width: 20,
        height: 20,
    },
    googleButtonText: {
        color: '#1f1f1f',
        fontSize: 16,
        fontWeight: '500',
        fontFamily: FONTS.body,
    },
    // Alternative compact social button styles (if you want to keep the icon-only version)
    socialButton: {
        width: 56,
        height: 56,
        borderRadius: RADII.rounded,
        backgroundColor: COLORS.glass,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: 'rgba(197, 198, 199, 0.1)',
        marginHorizontal: 8,
        ...SHADOWS.card,
    },
    socialButtonPressed: {
        ...SHADOWS.btnSecondaryHover,
        transform: [{ scale: 0.95 }],
    },
    bottomSection: {
        alignItems: 'center',
    },
    signUpText: {
        color: COLORS.text,
        fontSize: 16,
        fontFamily: FONTS.body,
        textAlign: 'center',
    },
    signUpLink: {
        color: COLORS.primary,
        fontWeight: '600',
        fontFamily: FONTS.body,
    },
});